# Generated by Django 4.2.7 on 2023-11-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
                ('Celular', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Fecha', models.DateField()),
                ('Tipod', models.CharField(choices=[('C.C', 'C.C'), ('C.E', 'C.E'), ('PAS', 'PAS'), ('TI', 'TI')], max_length=50)),
                ('N_documento', models.IntegerField()),
                ('Genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=50)),
                ('Edad', models.IntegerField()),
                ('Civil', models.CharField(choices=[('Casado', 'Casado'), ('Union libre', 'Union libre'), ('Soltero', 'Soltero')], max_length=50)),
            ],
        ),
    ]
