# Generated by Django 4.2.7 on 2023-11-30 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_delete_user'),
        ('hoja_vida', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refe_personales',
            name='Inforamcion_adi',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Funciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Informacion_Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inforamcion_adi', models.TextField()),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
